In [ ]:
# Tạo trang R trên colab: https://colab.research.google.com/notebook#create=true&language=r
a <- 5
b <- 7
c <- a + b

In [ ]:
fruit <- c("a",'b','c')

In [ ]:
print(fruit)

[1] "a" "b" "c"

In [ ]:
print(c)

[1] 12

In [ ]:
system("ls", TRUE)

[1] "sample_data"

In [ ]:
#https://drive.google.com/file/d/1Th3lPl_RCOQTs_JQSQGiVvj2TCjmO9tm/view?usp=sharing
system('gdown --id 1Th3lPl_RCOQTs_JQSQGiVvj2TCjmO9tm')

In [ ]:
print(getwd())

[1] "/content"

In [ ]:
#setwd()

In [ ]:
content=readLines('license.txt')

In [ ]:
print(content)

[1] "These data files are derived by splitting up the data set downloaded from:"
[2] "https://www.ontario.ca/data/ontario-public-schools-enrolment"
[3] "under the Open Government License - Ontario:"
[4] "https://www.ontario.ca/page/open-government-licence-ontario"

In [ ]:
#https://drive.google.com/file/d/1ndpmdo4vXwoHSpJnoiOom8H8zY4QCqdZ/view?usp=sharing
system('gdown --id 1ndpmdo4vXwoHSpJnoiOom8H8zY4QCqdZ')

In [ ]:
content_2=readLines('bai_tho.txt', encoding="UTF-8")

In [ ]:
print(content_2)

[1] "Mùa xuân là Tết trồng cây"
[2] "Làm cho đất nước càng ngày càng xuân"
[3] ""

In [ ]:
print(length(content))

[1] 4

In [ ]:
print(nchar(content))

[1] 74 60 44 59

In [ ]:
print(file.size("license.txt"))

[1] 242

In [ ]:
content_3=scan('license.txt','')

In [ ]:
print(content_3)

 [1] "These"
 [2] "data"
 [3] "files"
 [4] "are"
 [5] "derived"
 [6] "by"
 [7] "splitting"
 [8] "up"
 [9] "the"
[10] "data"
[11] "set"
[12] "downloaded"
[13] "from:"
[14] "https://www.ontario.ca/data/ontario-public-schools-enrolment"
[15] "under"
[16] "the"
[17] "Open"
[18] "Government"
[19] "License"
[20] "-"
[21] "Ontario:"
[22] "https://www.ontario.ca/page/open-government-licence-ontario"

In [ ]:
#https://drive.google.com/file/d/1Qep0c7pRIEzcQPYKAdcPHQZ0EKUygf43/view?usp=sharing
system('gdown --id 1Qep0c7pRIEzcQPYKAdcPHQZ0EKUygf43')

In [ ]:
df=read.table('Table0.txt')

In [ ]:
print(df)

        V1 V2  V3 V4 V5
1     Alex 25 177 57  F
2    Lilly 31 163 69  F
3     Mark 23 190 83  M
4   Oliver 52 179 75  M
5   Martha 76 163 70  F
6    Lucas 49 183 83  M
7 Caroline 26 164 53  F

In [ ]:
content2="Hello and welcome"
file_name=file(description="text.txt", open="a", encoding='UTF-8')
write(content2,file=file_name)

In [ ]:
content4=readLines('text.txt')
print(content4)

[1] "Hello and welcome" "Hello and welcome"

In [ ]:
#https://drive.google.com/file/d/1Blc5vw721i39mkM2La5IacCrx5Otzbcc/view?usp=sharing
system('gdown --id 1Blc5vw721i39mkM2La5IacCrx5Otzbcc')

In [ ]:
write.table(df, file="Table0_new.txt", sep="\t")

**CSV**

In [ ]:
#https://drive.google.com/file/d/1MMbExY4r4Pa7u3QKaehdl3EL7C3eRuES/view?usp=sharing
system('gdown --id 1MMbExY4r4Pa7u3QKaehdl3EL7C3eRuES')

In [ ]:
data=read.csv("emp.csv")

In [ ]:
head(data)

  id name     salary start_date dept
1  1 Rick     623.30 2012-01-01 IT
2  2 Dan      515.20 2013-09-23 Operations
3  3 Michelle 611.00 2014-11-15 IT
4  4 Ryan     729.00 2014-05-11 HR
5 NA Gary     843.25 2015-03-27 Finance
6  6 Nina     578.00 2013-05-21 IT

In [ ]:
data_IT=subset(data, dept=="IT")
head(data_IT)

  id name     salary start_date dept
1 1  Rick     623.3  2012-01-01 IT
3 3  Michelle 611.0  2014-11-15 IT
6 6  Nina     578.0  2013-05-21 IT

In [ ]:
print(is.data.frame(data))

[1] TRUE

In [ ]:
print(ncol(data))

[1] 5

In [ ]:
print(nrow(data))

[1] 8

In [ ]:
data_2014=subset(data, as.Date(start_date)>as.Date("2014-01-01"))

In [ ]:
print(data_2014)

  id     name salary start_date    dept
3  3 Michelle 611.00 2014-11-15      IT
4  4     Ryan 729.00 2014-05-11      HR
5 NA     Gary 843.25 2015-03-27 Finance
8  8     Guru 722.50 2014-06-17 Finance

In [ ]:
write.csv(data_IT, "data_IT.csv")

**EXCEL**

In [ ]:
install.packages('xlsx')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘rJava’, ‘xlsxjars’

In [ ]:
library('xlsx')

In [ ]:
#https://docs.google.com/spreadsheets/d/18PonYuffGf44SpAyuji3WmhSEjG051rk/edit?usp=sharing&ouid=100667830146032102250&rtpof=true&sd=true
system('gdown --id 18PonYuffGf44SpAyuji3WmhSEjG051rk')

In [ ]:
data=read.xlsx("emp_data.xlsx",sheetIndex=1)
print(data)

  id     name salary start_date       dept
1  1     Rick 623.30 2012-01-01         IT
2  2      Dan 515.20 2013-09-23 Operations
3  3 Michelle 611.00 2014-11-15         IT
4  4     Ryan 729.00 2014-05-11         HR
5        Gary 843.25 2015-03-27    Finance
6  6     Nina 578.00 2013-05-21         IT
7  7    Simon 632.80 2013-07-30 Operations
8  8     Guru 722.50 2014-06-17    Finance

In [ ]:
data_city=read.xlsx("emp_data.xlsx",sheetName='city')
print(data_city)

      name    city
1     Rick Seattle
2      Dan   Tampa
3 Michelle Chicago
4     Ryan Seattle
5     Gary Houston
6     Nina  Boston
7    Simon  Mumbai
8     Guru  Dallas

In [ ]:
write.xlsx(data_city, file='data_city.xlsx',sheetName='Sheet1', append=FALSE)

In [ ]:
new_data=read.xlsx('data_city.xlsx',sheetName="Sheet1")
print(new_data)

  NA.     name    city
1   1     Rick Seattle
2   2      Dan   Tampa
3   3 Michelle Chicago
4   4     Ryan Seattle
5   5     Gary Houston
6   6     Nina  Boston
7   7    Simon  Mumbai
8   8     Guru  Dallas